//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCRSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificationTracker
    {
        public int Id { get; set; }
        public string EmpBadgeNo { get; set; }
        public string CertificationCode { get; set; }
        public Nullable<System.DateTime> DateCertified { get; set; }
        public Nullable<System.DateTime> DateRecertified { get; set; }
    }
}
