//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCRSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Route
    {
        public string Employee_ID { get; set; }
        public string Employee_Name { get; set; }
        public string Cost_Center { get; set; }
        public string Checker_1_ID { get; set; }
        public string Checker_1_Name { get; set; }
        public string Checker_2_ID { get; set; }
        public string Checker_2_Name { get; set; }
        public string Approver_ID { get; set; }
        public string Approver_Name { get; set; }
    }
}
