//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCRSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDCR_Vw
    {
        public string Employee_ID { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Position { get; set; }
        public string Job_Status { get; set; }
        public Nullable<System.DateTime> PlanRecertificationDate { get; set; }
        public string HRCCell { get; set; }
        public string CurrentCell { get; set; }
        public string HRCSupervisor { get; set; }
        public string CurrentSupervisor { get; set; }
        public string EmploymentStatus { get; set; }
        public string PayrollType { get; set; }
        public Nullable<int> CertificateNumber { get; set; }
        public string Medal { get; set; }
    }
}
