//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCRSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDCR
    {
        public int Id { get; set; }
        public string BadgeNo { get; set; }
        public string HRCCell { get; set; }
        public string CurrentCell { get; set; }
        public string HRCSupervisor { get; set; }
        public string CurrentSupervisor { get; set; }
    }
}
