//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCRSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDCR_Vw
    {
        public string Employee_ID { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Position { get; set; }
        public string Cost_Center_Description { get; set; }
        public string Job_Status { get; set; }
        public string Supervisor { get; set; }
        public Nullable<System.DateTime> PlanRecertificationDate { get; set; }
    }
}
