//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCRSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class commonEmployeesEntities : DbContext
    {
        public commonEmployeesEntities()
            : base("name=commonEmployeesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employees_Details> Employees_Details { get; set; }
        public virtual DbSet<Emp_Route> Emp_Route { get; set; }
        public virtual DbSet<newlyEmployee> newlyEmployees { get; set; }
    }
}
