//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCRSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class lear_DailiesCertificationRequirementEntities : DbContext
    {
        public lear_DailiesCertificationRequirementEntities()
            : base("name=lear_DailiesCertificationRequirementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Certification> Certifications { get; set; }
        public virtual DbSet<CertificationHistory> CertificationHistories { get; set; }
        public virtual DbSet<CertificationTracker> CertificationTrackers { get; set; }
        public virtual DbSet<ReCertificationPlan> ReCertificationPlans { get; set; }
        public virtual DbSet<certificateTracker_Vw> certificateTracker_Vw { get; set; }
        public virtual DbSet<EmployeeDCR_Vw> EmployeeDCR_Vw { get; set; }
    
        public virtual ObjectResult<Nullable<System.DateTime>> GET_LastReCertificationPlanned(string badgeNo)
        {
            var badgeNoParameter = badgeNo != null ?
                new ObjectParameter("BadgeNo", badgeNo) :
                new ObjectParameter("BadgeNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("GET_LastReCertificationPlanned", badgeNoParameter);
        }
    
        public virtual ObjectResult<ReCertificationPlan> GETLatestPlan(string badgeNo)
        {
            var badgeNoParameter = badgeNo != null ?
                new ObjectParameter("BadgeNo", badgeNo) :
                new ObjectParameter("BadgeNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReCertificationPlan>("GETLatestPlan", badgeNoParameter);
        }
    
        public virtual ObjectResult<ReCertificationPlan> GETLatestPlan(string badgeNo, MergeOption mergeOption)
        {
            var badgeNoParameter = badgeNo != null ?
                new ObjectParameter("BadgeNo", badgeNo) :
                new ObjectParameter("BadgeNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReCertificationPlan>("GETLatestPlan", mergeOption, badgeNoParameter);
        }
    
        public virtual int deleteLastPlan(string bagdeNo)
        {
            var bagdeNoParameter = bagdeNo != null ?
                new ObjectParameter("BagdeNo", bagdeNo) :
                new ObjectParameter("BagdeNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteLastPlan", bagdeNoParameter);
        }
    
        public virtual int UpdateLDCRTablesWhenUpdateCertification(string oldCode, string newCode)
        {
            var oldCodeParameter = oldCode != null ?
                new ObjectParameter("OldCode", oldCode) :
                new ObjectParameter("OldCode", typeof(string));
    
            var newCodeParameter = newCode != null ?
                new ObjectParameter("NewCode", newCode) :
                new ObjectParameter("NewCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateLDCRTablesWhenUpdateCertification", oldCodeParameter, newCodeParameter);
        }
    }
}
