//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCRSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class newlyEmployee
    {
        public string Employee_ID { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Maiden_Name { get; set; }
        public string Birth_Date { get; set; }
        public string Birth_Place { get; set; }
        public byte Age { get; set; }
        public string Gender { get; set; }
        public string Civil_Status { get; set; }
        public string Marriage_Date { get; set; }
        public string Citizenship { get; set; }
        public string Religion { get; set; }
        public string Address_Street_No { get; set; }
        public string Address_Barangay { get; set; }
        public string Address_City { get; set; }
        public string Telephone { get; set; }
        public string Cellphone { get; set; }
        public string Email_Address { get; set; }
        public string Education_Level { get; set; }
        public string School { get; set; }
        public string Course { get; set; }
        public string Blood_Type { get; set; }
        public string SSS_No { get; set; }
        public string PhilHealth_No { get; set; }
        public string Bank { get; set; }
        public string Bank_Account_No { get; set; }
        public string TIN_No { get; set; }
        public string Tax_Code { get; set; }
        public string HDMF_No { get; set; }
        public string HDMF_Premium { get; set; }
        public decimal HDMF_Fixed_Contribution { get; set; }
        public string SSS_Premium { get; set; }
        public decimal SSS_Fixed_Contribution { get; set; }
        public string PhilHealth_Premium { get; set; }
        public decimal PhilHealth_Fixed_Contribution { get; set; }
        public string Contact_Person { get; set; }
        public string Contact_Relation { get; set; }
        public string Contact_Address_Street_No { get; set; }
        public string Contact_Barangay { get; set; }
        public string Contact_City { get; set; }
        public string Contact_Telephone { get; set; }
        public System.DateTime Cost_Center_Effectivity_Date { get; set; }
        public string Cost_Center_Code_HRC { get; set; }
        public string Cost_Center_Code_SAP { get; set; }
        public string Cost_Center_Description { get; set; }
        public string Employment_Status { get; set; }
        public System.DateTime Hire_Date { get; set; }
        public System.DateTime Regular_Date { get; set; }
        public string Location_Code { get; set; }
        public string Position { get; set; }
        public System.DateTime Position_Effectivity_Date { get; set; }
        public string Immediate_Superior { get; set; }
        public string Payment_Mode { get; set; }
        public string Payroll_Type { get; set; }
        public string Job_Status { get; set; }
        public bool Confidential { get; set; }
        public string Shift_Code { get; set; }
        public string WorkType { get; set; }
        public string WorkGroup { get; set; }
        public string Separation_Notice_Date { get; set; }
        public string Separation_Code { get; set; }
        public string Separation_Effectivity_Date { get; set; }
        public string Cleared_Date { get; set; }
        public Nullable<System.DateTime> Probationary_Date { get; set; }
        public string Employee_Type { get; set; }
        public Nullable<System.DateTime> Separation_System_Change { get; set; }
        public string Tax_Rate_Payroll_Type { get; set; }
        public string Tax_Rate_Effectivity_Date { get; set; }
        public Nullable<decimal> Tax_Rate { get; set; }
        public string Billing_Payroll_Type { get; set; }
        public string Billing_Effectivity_Date { get; set; }
        public Nullable<decimal> Billing_Rate { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string Provincial_Address_Street_No { get; set; }
        public string Provincial_Address_Barangay { get; set; }
        public string Provincial_Address_City { get; set; }
        public string Provincial_Telephone { get; set; }
        public string School_Awards { get; set; }
        public string PRC_License_No { get; set; }
        public string Extension_No { get; set; }
        public bool Anniversary { get; set; }
        public string Nickname { get; set; }
        public string Alternate_Account_Code { get; set; }
        public string Wife_Claim_Exemption { get; set; }
        public string Shoes_Size { get; set; }
        public string Shirt_Size { get; set; }
        public string Hair_Color { get; set; }
        public string Eye_Color { get; set; }
        public string Distinguishing_Mark { get; set; }
        public string Job_Level { get; set; }
        public string Pay_Class { get; set; }
        public string Include_in_Payroll { get; set; }
        public string Email { get; set; }
        public string Adu_AccountName { get; set; }
        public string status { get; set; }
        public string Dept_Man { get; set; }
        public Nullable<System.DateTime> PlanDateReCertification { get; set; }
        public string HRCSupervisor { get; set; }
        public string CurrentCell { get; set; }
        public string CurrentSupervisor { get; set; }
    }
}
