//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCRSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReCertificationPlan
    {
        public int Id { get; set; }
        public string Badge_No { get; set; }
        public string Lastname { get; set; }
        public string Firstname { get; set; }
        public string CertificationCode { get; set; }
        public System.DateTime PlanDate { get; set; }
        public string Confirmed { get; set; }
    }
}
