//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCRSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_vw
    {
        public Nullable<int> Badge_No { get; set; }
        public string Employee_ID { get; set; }
        public string Name { get; set; }
        public string Middle_Name { get; set; }
        public string Email { get; set; }
        public string Adu_AccountName { get; set; }
        public string Department_Code { get; set; }
        public string Department_Desc { get; set; }
        public string Plant { get; set; }
        public string Plant_Desc { get; set; }
        public string status { get; set; }
        public Nullable<bool> is_active { get; set; }
        public string Position { get; set; }
        public string Approver_ID { get; set; }
        public string Approver_Name { get; set; }
        public string Manager { get; set; }
        public string Employee_Password { get; set; }
    }
}
